all:  test-hashtable
	
error.o: error.c  

hashtable.o: hashtable.c 

test-hashtable.o : test-hashtable.c

test-hashtable: hashtable.o error.o test-hashtable.o
	gcc test-hashtable.o hashtable.o error.o -lcheck -lm -lrt -pthread -lsubunit -o test-hashtable

