all: test-hashtable
	
error.o: error.c

hashtable.o: hashtable.c

test-hashtable: hashtable.o error.o
	gcc hashtable.o error.o -lcheck -lm -lrt -pthread -lsubunit -o test-hashtable
	
clean:
	rm -f *.o core
	
mrproper: clean
	rm -f test-hashtable
